language: node_js
cache: yarn
script:
- yarn --version
deploy:
  provider: npm
  email: jenkins-reform@hmcts.net
  api_key:
    secure: VPVdo87eegkktV4MjMSQcQNIrgIarOp36PKpaQXk9GwObdZ5Il4VoBmYHAeHK8lAMvuiDh81Ur3xOz4ITywqGmt1lV8SNFJAtH/lr2US557ppsAvK/6mPDpAHivG5gDH0smi2itRBQqH+Bro+6a8WhYnJVySX8/lBzy2kyRsI80gyiYjBHaAlG835Tob5EzU41Lk0q2Ck+B6ZhIda4z9r4VTcmzQiusEkK+f5OGtgFw2UQbjj8XI+QnBPlZ1L5FwVTiQBt1jFUt/rnmQOGYlXxbBVUNm1DNoF/uGarkv+uIC3BfX9fk8b+wrTcgvv4q6SY91dgzzrLmxQXxZo0vKr+/C3Lu0f7m2dhDXBORyVyFHI/b2zhwgUgek/k7x+YIWdClEdMu378Xk+XbT8xncB4m0y4VGc3BuYeM8ausSoAO1RUosM8qBJGNHsoLTIrXoGzCrgsnril1coaXuzDgawLvojzCb481ahS6WadhyMwP0vBTgh3aVJuUXMJ5kduTpSTRbXSFwD6uciBOw2eSIN6CnHix7471BllQ3stCV8TGBY7ekJtMlTmHL2Ij5sqk5aog8TZOndhX6COquLuA+mOVX6P+V6BSnSGS8h5tsKUUH6E7iDZXmGmxJZhY41M3NQEQuz1cIuoBntpFgb9MfOmavifouhhB14GaLqzc+XkA=
  on:
    tags: true
    repo: hmcts/cmc-common-frontend
