language: node_js
cache: yarn
script:
- yarn --version
deploy:
  provider: npm
  email: jenkins-reform@hmcts.net
  api_key:
    secure: JZY4f4ZHTth23eepVwEnuMOUcANNM38rQkypsDspSwjbrL9Ijmyl6/7peeN/FWvEGVklrZxZdBtbmbtTwZ/pojztCQmCcIBIk6Oh8kSr2i4thYTPILvAHVkWawoFNJ08brG3Cr+U8iprXaY/ibq9sbc/rDGmLnKwCRFOSntaMWldy492WwiAZTZQYslNck6R8I+B2sbhxKc1Z+EYPZQniDCEX+bUwixGfogWf3PnnmWw9EYR1p+IsrgvHVKvDwGI2LIIGahv3+00vtC6cIM9wEZHa5TDZQr4SMAsNrFWQ1y0fkOxq8xLtemdw3iEtEAA+cC87j4v+vHNnnM8Vqs1RqNatlH72yJxlAd/qOa9lzAnh7T33aDden1nI1nWf7hSfzEpQ9jZ9CX9E0svw1lCg5zKMVPD9kVeVy0WjC4Ipyh7DzBvO6cX13+8VbL9jvkjQQgUuZBp7rLL1GbLB8R0E5/hYSTuSJQM//CWJPCrrQ1CF8IyPuTiYBQR+fgFrCPC+L1wB3PWyBJ7CUzGEYqe24R51n4YYAuyiYWYfXinfHNVbyDpkrKKjzce3dOG7ISHD0Q0hD/Qa6xLjQO6uYio8nE7qDeKuwNX+12n7nvWeZrB3ufCm3jZewwgiGUS7qKMGPYhlVnfkXh4uGlbpANyRHl6qXYmmHxowJQQTIjViSY=
  on:
    tags: true
    repo: hmcts/cmc-common-frontend
