language: node_js
cache: yarn
script:
- yarn --version
deploy:
  provider: npm
  email: jenkins-reform@hmcts.net
  api_key:
    secure: fItBO/z6ZLt54Fv41wnehmg84BQ8Ke2H43pIY66VlEce196DwAR2kyoXpAd8ED8HcyNGOnovcbamLu55L8fOzuJYfmiqsRDfzXtLxglWOtv1oE7+0xaMxkyioqLn4FXg9DHEK9r1+9wGBEKg+Z3uqrW5xuw0z+bz52mKygTTmlNak3uHM5Ll9/0t+SyTAbQ18MyR49y0TGOq5xeRlj2GBFPjnCODNVte6d6KwZ50VouWgnGPt+3FafbNRKdQ6cUQPj5kQSEuBmEVQOrJoiXCzIfrvawE3q+Om9rOh9CCt+w7lufsiRjUEfYjzv0YWv7A1CM8c9Lqn/61ZnfNwzlMGkT4qaQlNZQAKUIGgcQWac2CqF74wm0LN9uWeOSWY9ehPYqUQaKkG0ryFs7ygL2ZaC8M/G2mTVrkH7fwURr8wyyJao6D03WY1IJ1/m/dTjYbsDXlcPsdFSSF+5wejisWvL3+Ui6EdrvAS0b1LJ3M80ljC4PFOhyyU9SXsPxEmvqeDCnJ+2X7/W44s9ZPTfimI/nHAHtTUKes3BOULYtAgKkgs0fXtTpg953DfA+UJFyUpsa8zvKZSDHVlYnS3Z8YaZpA0oDEh2ugPWLvjuMApurmHWaGVK0gFpyMYoWjD3s/4z/r62k50BYLa3YmYUsh9bFy6ub8Qr2URx0Lk/1mWMw=
  on:
    tags: true
    repo: hmcts/cmc-common-frontend
